### ISSUE TITLE
자료구조 내용이 있으면 좋겠습니다.

### ISSUE THREAD

**Issue by kyupkyup** [brave-people/brave-tech-interview#22]

**Comment by KoEonYack** [comment]
@kyupkyup 

안녕하세요

본 repo에 처음으로 issue를 남겨주셔서 감사합니다 👍 

자료구조 내용 또한 중요한 내용으로 다루어야할 부분으로 생각하고 있습니다!

brave tech interview는 계속 새로운 기출문제를 풀고 있습니다.

유익하고 좋은 면접 기출문제 답변을 남길 수 있도록 하겠습니다!

감사합니다 :)
