### ISSUE TITLE
6. 운영체제, 스레드와 멀티스레드의 차이에 대하여

### ISSUE THREAD

**Issue by dimsssss** [brave-people/brave-tech-interview#31]
먼저 좋은 저장소를 잘 보고 있습니다. 감사합니다.

***한 스레드의 결과가 다른 스레드에 영향 끼칩니다. 크롬 하나의 탭에 문제가 생기면 없으면 크롬 자체를 다시 실행해야 하는 경우가 있습니다.***

크롬 탭은 각각의 PID를 부여받기 때문에 프로세스라고 알고 있습니다. 그런데 위의 문장을 보면 크롬 탭이 스레드처럼 보일 수 있다는 생각이듭니다. 스레드가 다른 스레드에 영향을 미치는 이유는 이미 작성하신 글에 나와있다고 생각합니다(***Stack만 별도의 메모리를 할당하며 Code, Data, Heap은 쓰레드간 공유합니다.***) 따라서 위의 내용은 없어도 되지 않을까요?

**Comment by KoEonYack** [comment]
@dimsssss 

정정해 주셔서 감사합니다. 크롬 탭은 PID를 부여받은 프로세스이기에 탭에 문제가 생긴 경우 크롬 전체가 죽지 않죠!

해당문구 제거하였습니다. 감사합니다! 👍
